require_relative "./config/environment"
require "sinatra/activerecord/rake"

desc "Run rackup server."
task :server do
  if ActiveRecord::Base.connection.migration_context.needs_migration?
    puts "Migrations are pending. Make sure to run `rake db:migrate` first."
    return
  end

  exec "bundle exec rerun -b -c 'rackup -s webrick config.ru'"
end


desc "Start the console"
task :console do
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  Pry.start
end
